apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lalternative-prod

resources:
  - namespace.yaml
  - s3-external-secret.yaml
  - www.yaml
  - ingress.yaml
  - network-policies.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: lalter
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: www
    includeSelectors: false
